pais:
    path:     /
    defaults: { _controller: "UsuarioBundle:pais:index" }

pais_show:
    path:     /{id}/show
    defaults: { _controller: "UsuarioBundle:pais:show" }

pais_new:
    path:     /new
    defaults: { _controller: "UsuarioBundle:pais:new" }

pais_create:
    path:     /create
    defaults: { _controller: "UsuarioBundle:pais:create" }
    methods:  POST

pais_edit:
    path:     /{id}/edit
    defaults: { _controller: "UsuarioBundle:pais:edit" }

pais_update:
    path:     /{id}/update
    defaults: { _controller: "UsuarioBundle:pais:update" }
    methods:  [POST, PUT]

pais_delete:
    path:     /{id}/delete
    defaults: { _controller: "UsuarioBundle:pais:delete" }
    methods:  [POST, DELETE]
