noticias:
    path:     /
    defaults: { _controller: "AppBundle:noticias:index" }

noticias_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:noticias:show" }

noticias_new:
    path:     /new
    defaults: { _controller: "AppBundle:noticias:new" }

noticias_create:
    path:     /create
    defaults: { _controller: "AppBundle:noticias:create" }
    methods:  POST

noticias_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:noticias:edit" }

noticias_update:
    path:     /{id}/update
    defaults: { _controller: "AppBundle:noticias:update" }
    methods:  [POST, PUT]

noticias_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:noticias:delete" }
    methods:  [POST, DELETE]
