app_admin_admin:
    resource: "@AppBundle/Resources/config/routing/pagina.yml"
    prefix:   /pagina

app_noticias:
    resource: "@AppBundle/Resources/config/routing/noticias.yml"
    prefix:   /noticias


app_homepage:
    resource: "@AppBundle/Resources/config/routing/default.yml"
    prefix:   /